robot:
  # Publish all joint states ----------------------------------- #always set to know state of robot
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joint1_position_controller: #name of controller
    type: effort_controllers/JointPositionController #type of controller for joint: output/input. i.e. controller takes in position as input and output effort
    joint: joint1
    pid: {p: 1.0, i: 0.01, d: 10.0}

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint2
    pid: {p: 1.0, i: 0.01, d: 10.0}

  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint3
    pid: {p: 1.0, i: 0.01, d: 10.0}

  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint4
    pid: {p: 1.0, i: 0.01, d: 10.0}

  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint5
    pid: {p: 1.0, i: 0.01, d: 10.0}

  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint6
    pid: {p: 1.0, i: 0.01, d: 10.0}