arm:  
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  arm_position_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - joint1
      - joint2
    