controller_list:
    # Make sure combination of <name> and <action_ns> (i.e. "<name>/<action>") is the full topic name shown with rostopic_list.
  - name: arm/arm_position_controller 
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint1
      - joint2
